train_test_split:
  test_size: 0.2
  random_state: 42
  stratify: true

# model_params:
#   output_dir: "data/08_reporting/results"
#   num_train_epochs: 1  
#   per_device_train_batch_size: 16
#   per_device_eval_batch_size: 16
#   warmup_ratio: 0.1
#   weight_decay: 0.01
#   logging_dir: "data/09_logs/roberta_base_logs"
#   logging_steps: 50
#   evaluation_strategy: "steps"
#   eval_steps: 100
#   save_strategy: "steps"
#   save_steps: 100
#   load_best_model_at_end: true
#   metric_for_best_model: "eval_loss"
#   learning_rate: 2e-5
#   fp16: true
#   gradient_accumulation_steps: 2
#   max_grad_norm: 1.0
#   dataloader_num_workers: 2
#   max_steps: 2500

# model_params:
#   output_dir: "data/08_reporting/results"
#   num_train_epochs: 1
#   per_device_train_batch_size: 8
#   per_device_eval_batch_size: 8
#   max_steps: 10
#   warmup_steps: 2
#   eval_strategy: "steps"
#   eval_steps: 5
#   save_steps: 5
#   logging_steps: 2
#   fp16: true

model_params:
  output_dir: "data/08_reporting/results"
  num_train_epochs: 1
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  max_steps: 20  # Longer than 10 but still quick
  warmup_ratio: 0.1
  weight_decay: 0.01
  evaluation_strategy: "steps"
  eval_steps: 10
  save_strategy: "steps"
  save_steps: 10
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  learning_rate: 2e-5
  fp16: true
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0
  dataloader_num_workers: 2